#ifndef _TOCTEXTDEF_
#define _TOCTEXTDEF_

enum {
    ERROR_TEXT_RESOLVEHOST,
    ERROR_TEXT_SOCKETCREATE,
    ERROR_TEXT_CONNECTSERVER,
    ERROR_TEXT_SERVERRESPOND,
    ERROR_TEXT_SERVERDISCONNECT,
    ERROR_TEXT_NOBLOCK,
    ERROR_TEXT_BLOCK,
    ERROR_TEXT_LOSTCONNECTION,
    ERROR_TEXT_AIMCLOSE,
    ERROR_TEXT_PROFILE_HOST,
    ERROR_TEXT_PROFILE_SOCKET,
    ERROR_TEXT_PROFILE_CONNECT,
    ERROR_TEXT_PROFILE_REQUEST,
    ERROR_TEXT_PROFILE_RESPOND,
    ERROR_TEXT_PROFILE_DISCONNECT,
    ERROR_TEXT_PROFILE_CORRUPT
};

enum
{
    WARN_TEXT_INFO,
    WARN_TEXT_USER,
    WARN_TEXT_LEVEL
};

enum
{
    SYSTEM_ERROR_TEXT_UNAVAILABLE,
    SYSTEM_ERROR_TEXT_NOWARN,
    SYSTEM_ERROR_TEXT_MESSAGELIMIT,
    SYSTEM_ERROR_TEXT_ACCOUNT,
    SYSTEM_ERROR_TEXT_PROCESS,
    SYSTEM_ERROR_TEXT_SERVICEDOWN,
    SYSTEM_ERROR_TEXT_TOOFAST,
    SYSTEM_ERROR_TEXT_MISSBIG,
    SYSTEM_ERROR_TEXT_MISSFAST,
    SYSTEM_ERROR_TEXT_BADLOGIN,
    SYSTEM_ERROR_TEXT_SERVICETEMPDOWN,
    SYSTEM_ERROR_TEXT_WARNINGHIGH,
    SYSTEM_ERROR_TEXT_CONNECTFAST,
    SYSTEM_ERROR_TEXT_UNKNOWNERROR,
    SYSTEM_ERROR_TEXT_NOTDEFINED,
    SYSTEM_ERROR_TEXT_UNKNOWNCOMMAND
};

enum
{
    SYSTEM_MISC_TEXT_SUCCESS,
    SYSTEM_MISC_TEXT_USERINFO,
    SYSTEM_MISC_TEXT_PAUSE,
    SYSTEM_MISC_TEXT_BUDDYUPDATE,
    SYSTEM_MISC_TEXT_GOTUSERNAME,
    SYSTEM_MISC_TEXT_GOTBUDDYLIST,
    SYSTEM_MISC_TEXT_GOTIM
};


extern char *ErrorText[];
extern char *WarnText[];
extern char *SystemErrorText[];
extern char *SystemMiscText[];
#endif

