name: Build DSAIM

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
   
    container:
      image: devkitpro/devkitarm:latest
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build Project
        run: make

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            *.elf
            *.nds
